collections:

  - name: redhat.satellite

  - name: redhat.rhv

  - name: vmware.vmware_rest
    version: 1.0.1

  - name: ansible.tower

  - name: ansible.netcommon

  - name: google.cloud

  - name: azure.azcollection

  - name: community.kubernetes
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.windows

  - name: community.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: community.general
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: community.vmware
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/
