collections:

  - name: redhat.satellite

  - name: redhat.rhv

  - name: vmware.vmware_rest
    version: 1.0.1

  - name: ansible.tower

  - name: ansible.netcommon

  - name: google.cloud

  - name: azure.azcollection

  - name: community.kubernetes
    

  - name: ansible.windows

  - name: community.windows
    

  - name: community.general
    

  - name: community.vmware
    
