collections:

  - name: redhat.satellite

  - name: redhat.rhv

  - name: ansible.tower

  - name: ansible.netcommon

  - name: google.cloud

  - name: community.kubernetes
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: community.general
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/