---
- name: Set facts if Windows chosen
  ansible.builtin.set_fact:
    vm_memory_terraform: 8192
    vm_template: 3e2117b4-3b6d-4d8a-bb4c-c2037682f2e2
    vm_tag: Windows
  when: operating_system == "Win2016"
  
- name: Set facts if RHEL8 chosen
  ansible.builtin.set_fact:
    vm_template: 4989a8d0-9ccd-4829-8b1a-7d63f82bede2
  when: operating_system == "RHEL8"

- name: Update terraform main file
  ansible.builtin.template: 
    src: templates/terraform.tf.j2
    dest: /terraform/ovirt/main.tf

- name: Block to handle error with disk
  block:    
    - name: Update State of VM to {{ terraform_state }} from template using Terraform
      community.general.terraform:
        project_path: "/terraform/ovirt/"
        state: "{{ terraform_state }}"
        force_init: yes
      register: terraformvms
  rescue:
      - name: Sleep for 10 seconds and continue with play
        wait_for:
          timeout: 10
        delegate_to: localhost
        
      - name: Update State of VM to {{ terraform_state }} from template using Terraform
        community.general.terraform:
          project_path: "/terraform/ovirt/"
          state: "{{ terraform_state }}"
          force_init: yes
        register: terraformvms

- name: Display Current Terraform VMs
  ansible.builtin.debug:
    msg: "{{ terraformvms | json_query('outputs.*.value') }}"

- name: Set stat for active vms
  ansible.builtin.set_stats:
    data:
      terraformactivevm: "{{ terraformvms | json_query('outputs.*.value') | join(',') }}"

- block:
  - name: Login to RHV
    redhat.rhv.ovirt_auth:
      hostname: "{{ rhvm_fqdn }}"
      username: "{{ rhvm_user }}"
      password: "{{ rhvm_password }}"
      ca_file: "{{ rhvm_cafile | default(omit) }}"
      insecure: "{{ rhvm_insecure | default(true) }}"
      
  - name: Tag a VM
    redhat.rhv.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_tag }}"
      state: attached
      vms: 
        - "{{ item }}"
    loop: "{{ vm_names }}"

  - name: Logout from RHV
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
      
  when: terraform_state == "present"