---
- name: Set facts if Windows chosen
  ansible.builtin.set_fact:
    vm_tag: Windows
    terraform_network: "LAN_01"
  when: operating_system == "Win2016"

- name: Sync with Gitrepo
  ansible.builtin.git:
    repo: 'git@github.com:shadowman-lab/Ansible-Terraform.git'
    dest: /tmp/terraform
    version: main
    accept_newhostkey: true
    key_file: /certs/id_ed25519

# Remove if desired to manually update terraform file
- name: Update terraform main file
  ansible.builtin.template:
    src: templates/terraformvmware.tf.j2
    dest: /tmp/terraform/vmware/main.tf
    owner: root
    group: root
    mode: '0644'
  when: terraformmain == "ansible"

- name: Decrypt files
  ansible.builtin.expect:
    command: 'ansible-vault decrypt terraform.tfstate terraform.tfstate.backup terraform.tfvars'
    chdir: /tmp/terraform/vmware
    responses:
      password: "{{ pah_pass }}"

- name: Update State of VM to {{ terraform_state }} from template using Terraform
  community.general.terraform:
    project_path: "/tmp/terraform/vmware/"
    state: "{{ terraform_state }}"
    force_init: true
  register: terraformvms

- name: Encrypt files
  ansible.builtin.expect:
    command: 'ansible-vault encrypt terraform.tfstate terraform.tfstate.backup terraform.tfvars'
    chdir: /tmp/terraform/vmware
    responses:
      password: "{{ pah_pass }}"

- name: Update git repo with terraform files
  ansible.builtin.shell: git add -A && git commit -m "Synching new files to repo" && git push
  args:
    chdir: /tmp/terraform

- name: Display Current Terraform VMs
  ansible.builtin.debug:
    msg: "{{ terraformvms | json_query('outputs.*.value') }}"

- name: Set stat for active vms if using gitops/manual update
  ansible.builtin.set_stats:
    data:
      vm_name: "{{ terraformvms | json_query('outputs.*.value') | join(',') }}"
  when: terraformmain == "gitops"

- name: Set fact for vmnames for tagging
  ansible.builtin.set_fact:
    vm_names: "{{ terraformvms | json_query('outputs.*.value') }}"
  when: terraformmain == "gitops"

- name: VMWare Tags block
  block:
    - name: Assign Tags
      community.vmware.vmware_tag_manager:
        tag_names:
          - "{{ tag }}"
        object_name: "{{ item }}"
        object_type: VirtualMachine
        state: add
        validate_certs: false
      loop: "{{ vm_names }}"

    - name: Loop to create group for linux hosts
      ansible.builtin.include_tasks: add_host_loop_vmware_terraform.yml
      loop: "{{ vm_names }}"
      when: operating_system is match("RHEL.*")

  when: terraform_state == "present"
