---
- name: Perform VM removal pre-steps
  hosts: "{{ vm_name }}"
  gather_facts: false
  collections:
    - redhat.satellite
    - community.general

  tasks:

  - name: See if host has IP before trying to unregister
    block:
      - name: Unregister system
        redhat_subscription:
          state: absent
          org_id: Shadow_Man
        when: ansible_host != ''

      - name: Remove from IDM
        command: "ipa-client-install --uninstall --unattended"
        when: ansible_host != ''
        register: output
        ignore_errors: true

      - name: Ensure host and its DNS record is absent for RHEL
        ipa_host:
          name: "{{ fqdn }}"
          state: absent
          ipa_pass: "{{ IPA_PASS }}"
          ipa_host: "{{ IPA_HOST }}"
          ipa_user: "{{ IPA_USER }}"
          update_dns: True
        when: ansible_host != ''

      - name: Delete hosts from Sat if RHEL
        host:
          name: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          server_url: "{{ server_url }}"
          state: absent
        delegate_to: localhost
    when: os_type is match("rhel.*")

  - name: Move Windows host to workgroup to disable in AD
    win_domain_membership:
      workgroup_name: removegroup
      domain_admin_user: "{{ domainuser }}"
      domain_admin_password: "{{ domainpassword }}" 
      state: workgroup
    ignore_unreachable: yes
    when: os_type is match("windows.*")

  - name: Delete Windows host from AD
    win_domain_computer:
      name: "{{ fqdn.split('.')[0] }}"
      state: absent
    delegate_to: "dc01.ad.shadowman.dev"
    when: os_type is match("windows.*")