---
- name: Remove VM From AD
  hosts: "{{ vm_name }}"
  gather_facts: false

  tasks:
  
    - name: Delete Windows host from AD
      win_domain_computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: "dc01.ad.shadowman.dev"
  