---
- name: Perform VM removal pre-steps
  hosts: "{{ vm_name }}"
  gather_facts: false
  collections:
    - redhat.satellite
    - community.general

  tasks:

  - name: See if host has IP before trying to unregister
    block:
      - name: Unregister system
        redhat_subscription:
          state: absent
          org_id: Shadow_Man
        when: ansible_host != ''

      - name: Remove from IDM
        ansible.builtin.command: "ipa-client-install --uninstall --unattended"
        when: ansible_host != ''
        register: output
        ignore_errors: true

      - name: Ensure host and its DNS record is absent for RHEL
        ipa_host:
          name: "{{ fqdn }}"
          state: absent
          ipa_pass: "{{ IPA_PASS }}"
          ipa_host: "{{ IPA_HOST }}"
          ipa_user: "{{ IPA_USER }}"
          update_dns: True
        when: ansible_host != ''

      - name: Delete hosts from Sat if RHEL
        redhat.satellite.host:
          name: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          server_url: "{{ server_url }}"
          state: absent
        delegate_to: localhost
    when: os is match("rhel.*")

  - name: Move Windows host to workgroup to disable in AD
    block:
      - name: Move Windows host to workgroup to disable in AD
        ansible.windows.win_domain_membership:
          workgroup_name: removegroup
          domain_admin_user: "{{ domainuser }}"
          domain_admin_password: "{{ domainpassword }}" 
          state: workgroup
        when: os is match("windows.*")
    rescue:
      - name: Retry Move Windows host to workgroup to disable in AD due to WINRM
        ansible.windows.win_domain_membership:
          workgroup_name: removegroup
          domain_admin_user: "{{ domainuser }}"
          domain_admin_password: "{{ domainpassword }}" 
          state: workgroup
        when: os is match("windows.*")

  - name: Remove Windows host from AD
    block:
      - name: Delete Windows host from AD
        community.windows.win_domain_computer:
          name: "{{ fqdn.split('.')[0] }}"
          state: absent
        delegate_to: "dc01.ad.shadowman.dev"
        when: os is match("windows.*")
    rescue:
      - name: Retry Delete Windows host from AD due to WINRM
        community.windows.win_domain_computer:
          name: "{{ fqdn.split('.')[0] }}"
          state: absent
        delegate_to: "dc01.ad.shadowman.dev"
        when: os is match("windows.*")

 