---
- name: Increase VM sotrage
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always

  tasks:
     
    - name: Get current CPU Sockets
      redhat.rhv.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name={{ vm_name }}
        fetch_nested: yes
        nested_attributes:
          - diskattachments
      register: result
      
  post_tasks:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
