---
- name: Create Snapshot on a VM
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always
  vars:
    datacenter: Default
    cluster: Default
    vm_names: "{{ vm_name.split(',') }}"

  tasks:
    - name: Create Snapshot on VM(s)
      ovirt_snapshot:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ vm_name }}"
        description: "{{ snapshot_desc }}"
        use_memory: false
        wait: yes
      register: snapshot
      loop: "{{ vm_names }}"

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
