---
- name: Increase VM sockets
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always

  tasks:
     
    - name: Restore virtual CPU sockets and cores
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: tower.shadowman.dev
        cpu_cores: 1
        cpu_sockets: 8
      
  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
