---
- name: Increase VM sockets
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always

  tasks:
     
    - name: Get current CPU Sockets
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name={{ vm_name }}
      register: result

    - name: Increase current virtual CPU sockets
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_name }}"
        cpu_cores: "{{ result.ovirt_vms[0].cpu.topology.sockets|int + 2 }}"
      
  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
