---
- name: Remove VM on RHV
  hosts: all
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      run_once: true
      tags:
        - always
  vars:
    datacenter: Default
    vm_names: "{{ vm_name.split(',') }}"

  tasks:
    - name: Stop VM
      redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ inventory_hostname }}"
        state: stopped

  post_tasks:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      run_once: true
      tags:
        - always