---
- name: Increase VM sotrage
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv
    
  pre_tasks:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always

  tasks:
     
    - name: Get VM Storage ID
      redhat.rhv.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name={{ vm_name }}
        fetch_nested: yes
        nested_attributes:
          - diskattachments
      register: result

    - name: Get Current VM Storage Size
      redhat.rhv.ovirt_disk_info:
        auth: "{{ ovirt_auth }}"
        pattern: id={{ result.ovirt_vms[0].disk_attachments[0].id }}
        fetch_nested: yes
        nested_attributes:
          - diskattachments
      register: storage

    - name: Set Size in GiB
      set_fact:
        storage_size: "{{ (storage.ovirt_disks[0].provisioned_size / 1073741824 + 2) | int}}GiB"

    - name: Set Storage Size for VM
      redhat.rhv.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        id: "{{ result.ovirt_vms[0].disk_attachments[0].id }}"
        state: attached
        vm_name: "{{ vm_name }}"
        size: "{{ storage_size }}"
      
  post_tasks:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
