---
- name: Pull Snapshots for a VM and create a restore job template
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    shadowman_snapshot: "pull"
    
  roles:
    - shadowman_snapshots