---
- name: Create VM on Satellite
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat.satellite

  vars:
    vm_names: "{{ vm_name.split(',') }}"
    host_group: "RHV_Image/RHEL7"
    imageid: "9"
    operatingsystem: "RHEL Server 7.7"

  tasks:

    - name: Change facts if wanting RHEL8
      ansible.builtin.set_fact:
        host_group: "RHV_Image/RHEL8"
        imageid: "11"
        operatingsystem: "10"
      when: operating_system == "RHEL8"

    - name: Create VM in Satellite
      redhat.satellite.host:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        name: "{{ item }}"
        hostgroup: "{{ host_group }}"
        compute_attributes:
          start: "1"
        organization: "Shadow Man"
        location: "Chattanooga"
        provision_method: "image"
        state: present
        build: true
        managed: true
      loop: "{{ vm_names }}"

