---
- name: Update VM on vSphere using Terraform
  hosts: localhost
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: "Terraformvsphere"
    terraform_state: "present"
    terraformmain: "gitops"
    operating_system: "ignore"

  roles:
    - shadowman_provision

- name: Perform hostname Set and reset agent to get FQDN on Linux
  hosts: just_created
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: "VMWare"

  roles:
    - shadowman_hostnameset
