---
- name: Remove VM
  hosts: "{{ vm_name | default('none') }}"
  gather_facts: false

  roles:
    - shadowman_deprovision

- name: Soft Delete VM
  hosts: localhost
  gather_facts: false

  roles:
    - shadowman_soft_delete
