---
- name: Remove VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
    vm_names: "{{ vm_name.split(',') }}"

  tasks:

  - name: Look up the VM in the inventory
    register: search_result
    vmware.vmware_rest.vcenter_vm_info:
      filter_names: "{{ vm_names }}"

  - name: Delete some VM
    vmware.vmware_rest.vcenter_vm:
      state: absent
      vm: '{{ item.vm }}'
    with_items: '{{ search_result.value }}'