---
- name: Create VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_id: domain-c26
    datastore_id: datastore-38
    folder_id: group-v28
    resource_pool_id: resgroup-27
    vm_names: "{{ vm_name.split(',') }}"
    source_vm_id: vm-46
    
  tasks:
    - name: Change facts if running Windows
      set_fact:
        source_vm_id: vm-47
      when: guest_OS == "WINDOWS_9_SERVER_64"

    - name: Change facts if running RHEL8
      set_fact:
        source_vm_id: vm-45
      when: guest_OS == "RHEL_8_64"
     
    - name: Create and run VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          cluster: '{{ cluster_id }}'
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: "{{ item }}"
        state: clone
        power_on: "{{ powered_on }}"
        source: "{{ source_vm_id }}"
        guest_OS: "{{ guest_OS }}"
      loop: "{{ vm_names }}"