---
- name: Create VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_id: "Cluster1"
    datastore_id: "NFS_Cersei"
    folder_id: "Shadowman/Discovered virtual machine"
    resource_pool_id: "Cluster1"
    vm_names: "{{ vm_name.split(',') }}"
    source_vm_id: "RHEL7_ShadowMan"
    
  tasks:
    - name: Change facts if running Windows
      set_fact:
        source_vm_id: "Win2016_ShadowMan"
      when: guest_OS == "WINDOWS_9_SERVER_64"

    - name: Change facts if running RHEL8
      set_fact:
        source_vm_id: "RHEL8_ShadowMan"
      when: guest_OS == "RHEL_8_64"
     
    - name: Create and run VM
      community.vmware.vmware_guest:
        cluster: '{{ cluster_id }}'
        datastore: '{{ datastore_id }}'
        folder: '{{ folder_id }}'
        resource_pool: '{{ resource_pool_id }}'
        name: "{{ item }}"
        power_on: true
        state: poweredon
        template: "{{ source_vm_id }}"
        wait_for_ip_address: yes
      loop: "{{ vm_names }}"