---
- name: Create VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster: "{{ my_cluster_info.id }}"
    datastore: "{{ my_datastore.datastore }}"
    folder: "{{ my_virtual_machine_folder.folder }}"
    resource_pool: "{{ my_cluster_info.value.resource_pool }}"
    vm_names: "{{ vm_name.split(',') }}"
    source_vm_id: "test"
    
  tasks:
    #- name: Change facts if running Windows
    #  set_fact:
    #    source_vm_id: 
    #  when: guest_OS == "Windows64"

    #- name: Change facts if running RHEL8
    #  set_fact:
    #    source_vm_id: 
    #  when: guest_OS == "RHEL_8_64"
     
    - name: Create and run VM
      vmware.vmware_rest.vcenter_vm:
        vcenter_validate_certs: False
        placement:
          cluster: '{{ cluster_id }}'
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: "{{ item }}"
        power_on: "{{ powered_on }}"
        source: "{{ source_vm_id }}"
        guest_OS: "{{ guest_OS }}"
      loop: "{{ vm_names }}"