---
- name: Create VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster_id: "Cluster1"
    datastore_id: "NFS_Cersei"
    folder_id: "Discovered virtual machine"
    vm_names: "{{ vm_name.split(',') }}"
    source_vm_id: "RHEL7_ShadowMan"
    
  tasks:
    - name: Change facts if running Windows
      set_fact:
        source_vm_id: "Win2016_ShadowMan"
      when: guest_OS == "WINDOWS_9_SERVER_64"

    - name: Change facts if running RHEL8
      set_fact:
        source_vm_id: "RHEL8_ShadowMan"
      when: guest_OS == "RHEL_8_64"
     
    - name: Create and run Linux VM
      community.vmware.vmware_guest:
        cluster: '{{ cluster_id }}'
        datastore: '{{ datastore_id }}'
        folder: '{{ folder_id }}'
        datacenter: "Shadowman"
        name: "{{ item }}"
        state: "{{ state }}"
        template: "{{ source_vm_id }}"
        wait_for_ip_address: yes
      loop: "{{ vm_names }}"
      when: guest_OS is match("RHEL.*")

    - name: Create and run Windows VM
      community.vmware.vmware_guest:
        cluster: '{{ cluster_id }}'
        datastore: '{{ datastore_id }}'
        folder: '{{ folder_id }}'
        datacenter: "Shadowman"
        name: "{{ item }}"
        state: "{{ state }}"
        template: "{{ source_vm_id }}"
        wait_for_ip_address: yes
        customization:
          domain: ad.shadowman.dev
          autologon: true
          hostname: "{{ item.split('.')[0] }}"
          productid: "{{ productid }}"
          password: "{{ windowspassword }}"
      loop: "{{ vm_names }}"
      when: guest_OS is match("WINDOWS.*")