---
- name: Remove VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
    vm_names: "{{ vm_name.split(',') }}"

  tasks:

  - name: Loop to remove hosts
    include_tasks: delete_host_loop_vmware.yml
    loop: "{{ vm_names }}"