---
- name: Remove VM on VMWare
  hosts: "{{ vm_name | default('none') }}"
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: "VMWare"

  roles:
    - shadowman_deprovision

- name: Soft Delete VM
  hosts: localhost
  gather_facts: false

  roles:
    - shadowman_soft_delete
