---
- name: Pull VM facts from VMWare
  hosts: localhost
  gather_facts: false
  vars:
    cluster_name: 'Cluster1'
    datastore_name: 'NFS_Cersei'

  tasks:

    - name: Get virtual machine info
      vmware.vmware_rest.vcenter_vm_info:
      register: vm_info

    - name: Get Cluster info
      vmware.vmware_rest.vcenter_cluster_info:
        filter_names:
        - "{{ cluster_name }}"
        vcenter_validate_certs: no
      register: cluster_info

    - name: Get Resource info for {{ cluster_name }}
      vmware.vmware_rest.vcenter_cluster_info:
        vcenter_validate_certs: no
        cluster: "{{ cluster_info.value[0].cluster }}"
      register: resource_pool_info

    - name: Get datastore info
      vmware.vmware_rest.vcenter_datastore_info:
        vcenter_validate_certs: no
        filter_names:
        - "{{ datastore_name }}"
      register: datastore_info

    - name: Get folder info
      vmware.vmware_rest.vcenter_folder_info:
        vcenter_validate_certs: no
        filter_names:
        - '{{ folder_name }}'
      register: folder_info