---
- name: Create VM on VCenter
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster: "{{ my_cluster_info.id }}"
    datastore: "{{ my_datastore.datastore }}"
    folder: "{{ my_virtual_machine_folder.folder }}"
    resource_pool: "{{ my_cluster_info.value.resource_pool }}"
    vm_names: "{{ vm_name.split(',') }}"
    
  tasks:
    #- name: Change facts if running Windows
    #  set_fact:
    #    vm_memory: 8GiB
    #    vm_tag: Windows
    #  when: operating_system == "Win2016"
     
    - name: Create and run VM
      vmware.vmware_rest.vcenter_vm:
        vcenter_validate_certs: False
        placement:
          cluster: '{{ cluster_id }}'
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: "{{ item }}"
        power_on: yes
        source: "{{ source_vm_id }}"
        guest_OS: "{{ guest_OS }}"
      loop: "{{ vm_names }}"