---
- name: Wait for host to generate IP/FQDN
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    - vm_names: "{{ vm_name.split(',') }}"

  tasks:

    - name: Look up the VM in the inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names: "{{ vm_names }}"

    - name: Collect information about VMs
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ item.vm }}'
      register: vm_info
      loop: "{{ search_result.value }}"

    - name: Wait until my VM is ready
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: "{{ item.id }}"
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "RUNNING"
      retries: 60
      delay: 5
      loop: "{{ vm_info }}"

    

    