---
- name: Wait for host to generate IP
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.rhv

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"

  vars:
    - vm_names: "{{ vm_name.split(',') }}"

  tasks:

    - name: Test for IP address
      ovirt_nic_info:
        vm: "{{ item }}"
        fetch_nested: yes
        nested_attributes:
          - ips
        name: nic1
        auth: "{{ ovirt_auth }}"
      register: results
      until:  results.ovirt_nics[0].reported_devices[0].ips[0].address is defined
      retries: 60
      delay: 10
      loop: "{{ vm_names }}"

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
