---
- block:
  - name: Login to RHV
    redhat.rhv.ovirt_auth:
      hostname: "{{ rhvm_fqdn }}"
      username: "{{ rhvm_user }}"
      password: "{{ rhvm_password }}"
      ca_file: "{{ rhvm_cafile | default(omit) }}"
      insecure: "{{ rhvm_insecure | default(true) }}"
    
  - name: Get current MEM info
    redhat.rhv.ovirt_vm_info:
      auth: "{{ ovirt_auth }}"
      pattern: name={{ vm_name }}
    register: result

  - name: Increase current virtual Memory
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      memory: "{{ result.ovirt_vms[0].memory|int / 1048576 + 256 | string}}MiB"
    
  always:
  - name: Logout from RHV
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"