--- 
- block:
  - name: Login to RHV
    redhat.rhv.ovirt_auth:
      hostname: "{{ rhvm_fqdn }}"
      username: "{{ rhvm_user }}"
      password: "{{ rhvm_password }}"
      ca_file: "{{ rhvm_cafile | default(omit) }}"
      insecure: "{{ rhvm_insecure | default(true) }}"
     
  - name: Create and run VM from template
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ operating_system }}_updates.shadowman.dev"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{ vm_memory }}"
      high_availability: true
      state: running
      wait: yes
      
  always:
  - name: Logout from RHV
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"