---
- name: Get VM info
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
    - "{{ inventory_hostname }}"
    vcenter_validate_certs: no
  register: vm_info
  delegate_to: localhost

- name: Collect id about a specific VM
  vmware.vmware_rest.vcenter_vm_info:
    vm: "{{ vm_info.value[0].vm }}"
    vcenter_validate_certs: no
  register: vm_full_info
  delegate_to: localhost

- name: Restore cores to the VM
  vmware.vmware_rest.vcenter_vm_hardware_cpu:
    vm: '{{ vm_full_info.id }}'
    count: '{{ cpu_cores }}'
    vcenter_validate_certs: no
  delegate_to: localhost
