---
- name: Move Windows host to workgroup to disable in AD
  block:
    - name: Move Windows host to workgroup to disable in AD
      ansible.windows.win_domain_membership:
        workgroup_name: removegroup
        domain_admin_user: "{{ domainuser }}"
        domain_admin_password: "{{ domainpassword }}" 
        state: workgroup
  rescue:
    - name: Retry Move Windows host to workgroup to disable in AD due to WINRM
      ansible.windows.win_domain_membership:
        workgroup_name: removegroup
        domain_admin_user: "{{ domainuser }}"
        domain_admin_password: "{{ domainpassword }}" 
        state: workgroup
  always:
    - name: Delete Windows host from AD
      community.windows.win_domain_computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: "dc01.ad.shadowman.dev"