---
- name: Remove instance
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ inventory_hostname }}"
    state: absent

- name: Delete network interface
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ network_interface }}"
    state: absent

- name: Delete Security Group
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ security_group }}"
    state: absent