---
- block:
  - name: Login to RHV
    redhat.rhv.ovirt_auth:
      hostname: "{{ rhvm_fqdn }}"
      username: "{{ rhvm_user }}"
      password: "{{ rhvm_password }}"
      ca_file: "{{ rhvm_cafile | default(omit) }}"
      insecure: "{{ rhvm_insecure | default(true) }}"
    delegate_to: localhost
    run_once: true

  - name: Stop VM
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ inventory_hostname }}"
      state: stopped
      wait: yes
    delegate_to: localhost

  - name: Delete VM
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ inventory_hostname }}"
      state: absent
      wait: yes
    delegate_to: localhost

  always:
  - name: Logout from RHV
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
    delegate_to: localhost
    run_once: true